spring:
  profiles: prod
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://database-1.czh5fahyf9wh.ap-northeast-2.rds.amazonaws.com:3306/dev_timeline
      username: admin
      password: nm0523679
      driver-class-name: com.mysql.cj.jdbc.Driver
#      auto-commit: false
#      connection-test-query: SELECT 1
#      minimum-idle: 10
#      maximum-pool-size: 50
#      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
#      pool-name: pool-timeline
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties.hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

  main:
    allow-bean-definition-overriding: true

selenium:
  web-driver-path: /usr/local/bin/chromedriver