spring.profiles.include: local
server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:sky7th
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /test_db

  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

selenium:
  web-driver-path: C:\\chromedriver\\chromedriver.exe