spring:
  profiles: local

  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    properties:
      show_sql: true
      format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 660641647489-3tvclq6bu93546110lnrv1v0rbbnbj6j.apps.googleusercontent.com
            client-secret: 3adRqjinELMl40Ah_4MVnwVA
          github:
            client-id: 3a5fd8be9a929bbac08d
            client-secret: 1dd82c3ed618452083df2cce6c9fc924e878010e

restTemplate:
  factory:
    readTimeout: 5000
    connectTimeout: 3000
  httpClient:
    maxConnTotal: 100
    maxConnPerRoute: 5

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000

  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect