name: DEPLOY DEV-TIMELINE BATCH

on:
  push:
    branches: [ master ]
    paths:
      - 'dev-timeline-batch/**'
      - 'dev-timeline-crawlpost/**'
      - 'dev-timeline-generalpost/**'
      - 'dev-timeline-post/**'
      - 'dev-timeline-user/**'
      - 'dev-timeline-core/**'

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

env:
  PROJECT_NAME: dev-timeline-batch
  BUCKET: dev-timeline-deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :${PROJECT_NAME}:clean :${PROJECT_NAME}:build
      - name: MAKE DEPLOYMENT DIR
        run: mkdir -p code-deploy-${PROJECT_NAME}
      - name: MOVE DEPLOY CODE DEPLOY SCRIPT
        run: cp ${PROJECT_NAME}/code-deploy/* code-deploy-${PROJECT_NAME}/
      - name: MOVE BUILD JAR
        run: cp ${PROJECT_NAME}/build/libs/*.jar code-deploy-${PROJECT_NAME}/
      - name: ZIP CODE DEPLOY
        run: zip -r -j code-deploy-${PROJECT_NAME} code-deploy-${PROJECT_NAME}/*
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Upload to S3
        run: aws s3 cp code-deploy-${PROJECT_NAME}.zip s3://${BUCKET}/${PROJECT_NAME}/${PROJECT_NAME}-${GITHUB_SHA}.zip --region ap-northeast-2
      - name: Code Deploy
        run: aws deploy create-deployment --application-name ${PROJECT_NAME}-deploy --deployment-group-name ${PROJECT_NAME}-deploy-prod --region ap-northeast-2 --s3-location bucket=${BUCKET},bundleType=zip,key=${PROJECT_NAME}/${PROJECT_NAME}-${GITHUB_SHA}.zip
      - name: Clear Deploy DIR
        run: rm -rf code-deploy-${PROJECT_NAME}
